language: python
python: 3.6.7
script:
- python ./Source/test.py
env:
  global:
    secure: JN23SBK6U/qaGxgBO2RclU20MRMmfKEPBW+Ijb4b4fNMZaPRsvJcrHZ9uiWIv3HbzzsUqKtdlEIMbmsqYQfCcjqL8Zr+AjcVf2Q2T6sxvLeHKB7ZyLzYpWF7biN3uG16A0C3u4tzN2Pa8fyufNleVjt6k+DQwLI2ebcYq+HL8GducLUm/RkSFHoTb3IUek7AV3M2RQv3TvtUnSVF+ACfiMbYycOC5fY8KNY2qBNssDjoIXGoJ7i2yJmlVg3w9UFVRtc7yzgXKlmq6/z55nGB0AqlCByuZ6mM3T8ZKT7R0wZKbYFriRLTKFFbyk4DQ3s4C1uOVSWf4NS+5eAfBG1y8TBr8EDmMm5JlK1o0RRDicwjvgB9M/zGZnM45gyFOu5/Low3l0PWSg6WMu2cfLArJG7UICw4IZ6CHYWcJIQ3LoOnV+nlPlyECH1tIkAcf/NdWqLhQnOM15f4kcnDsz2by4LQVMA3KspT8bQheiMuE2bge7RHmsBzGYDH6QxifEzYKkwmTOz4Q+2D5nhvVgeVPQ0pthROF+NGCrILG/1qvUnDHU3bbd8aUTCVhv8m7FkCLzP19SAUhZMmhbGvCwP3jFEheo9cQeRoWZLLLYAEEf34Jl7nY382gG0VBN5085RgZHOgs6sejN2nrqOsM+RIYC1r/DQ+xfUalfl6BYdkQcg=
