language:          python

python:
  - 3.6.6

branches:
  - master

install:
  - pip install -r requirements.txt

before_script:
  - cd code

script:
  - python Echo2.py

before_deploy:
  - cd ..
  - git clone https://github.com/hfagerlund/mkdocs-docskimmer.git
  - cp -r $PWD/mkdocs-docskimmer/mkdocs_docskimmer .
  - cp -r $PWD/mkdocs-docskimmer/mkdocs_docskimmer/. ./docs
  - mkdocs build --verbose --clean

deploy:
  provider:        pages
  skip_cleanup:    true
  github_token:    "$github_token"
  local_dir:       site
  on:
    branch:        master

notifications:
  email:           false

env:
  global:
    secure:        cVtqqJDNM+V1u4H46wJmeQHZdeTOilu7IclLN6t3dRVmDYJaomxy42IEAaHlPaCyEwOUOVAAC8Juqzn3ET2sBUPm86ueABAjLsjUbgJ8PrpPLF6ilT7eRTZUKOLUXAGlPP61hDRlqjTLoIPOLPQi+Fsk7MrjsrbNe3GIQ4Gafqbh5uYW5SjMjOBsh9mzZCXkqfkLPynRLWlcrEhiQn8J+klvI3V58VhJH/04SZAKTKsn8gMpalFlemd1RvQzvYj+n5w6kA0cbgmXn6JX5Yen1Nrju5QARlA9lr6bPSvkyBmRQjUxEgqqPpwvGYPqXXPBuZ7/gRctuq/dwvfjRCL4pcrndIGTI9ozQrFJljfLK5Uqvxay9EGPwLW/S6Usbj3fEYdBS/WUzx28BR+cXsYYQTEWk61ejqZ2GE25wfYk55TiKrPBhZ1ScaI5cE6gv8WmzbrcfG0yUl1HcX6sJv/db0q783O9Mhqa1Xf45XQFTf0oB9irDKt0pHMFhbCprZO7nzJT/kM2GaUIsnP/lXRpp1rNSIF5ZUOLciSCeLpYIrsu0poiYVfKG9CsjwcIlEU9WeoulGDjTVKhfltQ9QMVQaUv+d3QUku6qMagi4UNJQf7tzSfoPLH8vngtvcc5snEZ9ANPHozd00+nrQKlnuUig6LbwmUejupBdo+7QbyIlg=

