language:                   python

python:                     3.6.7

cache:                      pip

jobs:
  include:
    - stage:                Testing

      install:
          - pip install -r requirements.txt

      script:
          - python Source/test.py

    - stage:                Deployment

      if:                   type != pull_request AND tag IS present

      install:
          - pip install pyminifier pbr

      before_script:
          - cd Source

      script:
          - find echo_lang -type f -name "*.py" -exec pyminifier --lzma --obfuscate-variables --outfile="{}" "{}" \;

      deploy:
          - provider:       pypi
            user:           "eevee1"
            password:       "$pypi_password"
            skip_cleanup:   true
            server:         https://test.pypi.org/legacy/
            distributions:  "sdist bdist_wheel"
            on:
                tags: true

          - provider:       pypi
            user:           "eevee1"
            password:       "$pypi_password"
            skip_cleanup:   true
            distributions:  "sdist bdist_wheel"
            on:
                tags: true

env:
    global:
        - secure: t3i2Y/s5xzKDRzPiDroKrolKgb+yKTau0S30ZWSN/XvHuz90Qv4ZJHToLz+kJRhCkOkELrazipuciQc25i764LKyCk3kUKiGd5Hw1BkxXIVdQCkzStfqnA2RgZWwXMe5i8VN6s5jFaw5ZyPJU6ur0DX8rCZPVJKETK6I+iYyNrXK7afyxJKhE6jJRXlTtf4gthZdI8sfd+uvWT9ztyqXqnJNc7le1MPXzgaZKup1xKBsivqfGOrYQOr1h5ximcM/Cce6s8pPPw52Edr3Mma2h2gVPfHsOKluYeWttza2Us/V48Us8PxjS8G5ewMSlS+PPn6MiX7D4BIhK/kkFHBVsXv81yYUJFkatqEwTNmwg7iTAYhT/ctmEo6CSg4+Uwdraz9nx4yzbo0X+iJfmY75wUera+3VsA9qFxNnWu9hjSXU5imRwKKyLW/oUIha9gqhRRy3Yg5vlcSIfY4sJ6J/MdjjaRaFnVAinLnvXrHZZ+m96sRVwC78iHLSwFsbH7GIxONeMxPHHur3riDXlLBuDIpjJD0dUx+uQka+cTZlAxwc2oAw6ub8ugxmupdhjCKTbRCdttmviQwJvqXTFmZzGbaDMiwxd2kb4ZwYgnEzkz75zSpLG7J5Lv4J2G7EIolcwYwMJ0UdotEEWODE7xdCiyYhzzzDf1dIM4+jNUPnCmo=
