language:                   python

python:                     3.6.7

cache:                      pip

jobs:
  include:
    - stage:                Testing

      install:
          - pip install -r requirements.txt

      script:
          - python Source/test.py

    - stage:                Deployment

      if:                   type != pull_request AND tag IS present

      install:
          - pip install pyminifier pbr

      before_script:
          - cd Source

      script:
          - find echo_lang -type f -name "*.py" -exec pyminifier --lzma --obfuscate-variables --outfile="{}" "{}" \;

      deploy:
          - provider:       pypi
            user:           "eevee1"
            password:       "$jNUPnCmo"
            skip_cleanup:   true
            server:         https://test.pypi.org/legacy/
            distributions:  "sdist bdist_wheel"
            on:
                tags: true

          - provider:       pypi
            user:           "eevee1"
            password:       "$jNUPnCmo"
            skip_cleanup:   true
            distributions:  "sdist bdist_wheel"
            on:
                tags: true

env:
    global:
        - secure: mqg/FhuC5tmnXom/0uvFbVtKYtqZxwBXPXW/6fB78NIPIcp+MI2IzqbO19/pqLb6uyFtaZR+u6FV6LJoiuEm2k06OrA3gdH2hTHU6FDWIVwB0+yK4YE/PnHfNNYQmVT9Rd6Sj3G1hMc1GBdNGUEoTqEgBOMalTNjPabIVSVhjk6deMJnYohmZOwXv9NPHfSxiWTcHxuE4/G3JVikMvakDc0Rg1va3LNz3Wrdyzm11Y/fjiJz4aHcGG/CxtSN/XBeXeTks1nOOIpzx0NzHplztfs5I4PmbENceWZDu+p4AZW0YWFEkJ30hbpLGDKAIDbmFmvMIhqAHe2HiktCuRim4rNzBOosUyi9ZpytdeSQeucPwL6A5by2gxH+DFtyTLsiVXBCJ20l2/hGk51FlRB6bGe2L0Q1BZ3dnEpCj+AunuTA1MLx2BI8CT/v6s6JY29+bfbkK9+Cfw1SJptPqdocRDdkcuGtaoAESHhe8sy2WJvEkgpsWodkoKWUdjwEl2L0ZlB+m+3+Zms/6IdHUzQ2hbDpvRlWLGCRGhA59RUVEMfST4eqlBCWAsftSkBZ1T5GSNz5qHzE6d5Sj0El5tq33py2HHLVfDzkuv30YI69w/mhrv1EWOQQbNVq/PIFmvqXeLwhCbUIdIQeOHerMqareBvdD9ic0x4QtUnc7Arpf7Y=
