language:                   python

python:                     3.6.7

cache:                      pip

jobs:
  include:
    - stage:                Testing

      install:
          - pip install -r requirements.txt

      script:
          - python Source/test.py

    - stage:                Deployment

      if:                   type != pull_request AND tag IS present

      install:
          - pip install pyminifier pbr

      before_script:
          - cd Source

      script:
          - find echo_lang -type f -name "*.py" -exec pyminifier --lzma --obfuscate-variables --outfile="{}" "{}" \;

      deploy:
          - provider:       pypi
            user:           "eevee1"
            password:       $pypi_password
            skip_cleanup:   true
            server:         https://test.pypi.org/legacy/
            distributions:  "sdist bdist_wheel"
            on:
                tags: true

          - provider:       pypi
            user:           "eevee1"
            password:       "$pypi_password"
            skip_cleanup:   true
            distributions:  "sdist bdist_wheel"
            on:
                tags: true

env:
    global:
        - secure: "GNuVTuxyJZk/H7ENadXr6i4ROZ8cWD6fvjKGfO7vphjCYYVnba0n4XpEaZdpQKTlIBhy/SRk7kQ2G3OHe4i6ZFOZztKNPe/YCOVBCSf48GetFo13afdfFVqit8NYRILpvIREMAupXAuTBx48qWA5fmuw9Ry0ZQa7H6KecfBUMeqGQYha9H97TFRRKdJaIScQj+NPQcdVnDCznqKWmnyxpYIasMh63/KZSofjypjf7nbN5qxJIDkQezwjz/tOLg84rcksZXU2eoRFGrlLwxxD0a5ClzAniilePUo67BTUauQL2zylZo5E68CT6kA3TXPPw4Q7tOhL8vp9orl7AHAmy+z/fwkBfta9EnWh6MxYchDcvzEMRbv4dC0UWY5miywbl331kYThEfwMr3KS9fK+yUjBtbf6bjxMegf07cPnhwF3QekZ5GSoFBFPO9Z34qfgqZJnMHAsDfZqv67/g5RayUAIaBFOPlfi8woumfn43tgn6Q6IKpeik8Do+PBl5lrr0XaIGy4+h+9QHPLJi6JvhsDfYYCUMjpmLoJ7LaZt3ij9ybnY01JZQp+47e6BWNBuiovPRB/K/hnVPMjOyRpCPVI7LDNo7HvsvPK76+jrXD9iVRfjxe+aIxpW8fog9G/VrwRmR5yoDO7CtDM/vArd5ZPXwLMU1mM2B8IOKdXuEQ0="
