language:                   python

python:                     3.6.7

cache:                      pip

jobs:
  include:
    - stage:                Testing

      install:
          - pip install -r requirements.txt

      script:
          - python Source/test.py

    - stage:                Deployment

      if:                   type != pull_request AND tag IS present

      install:
          - pip install pyminifier pbr

      before_script:
          - cd Source

      script:
          - find echo_lang -type f -name "*.py" -exec pyminifier --lzma --obfuscate-variables --outfile="{}" "{}" \;

      deploy:
#          - provider:       pypi
#            user:           "eevee1"
#            password:
#                secure: qgDrBxXn2QVfyC1Q/TqCVlX9rLjuPQKhVyBtPKofn1NNysWLBDCWb0HJtdqntv4JLVY/CeeFPpJhWA476CUq/jvlkk+oS0WlKXucL9hDybo3cQqlAUrPx+Hxkxv4eNJTbKYG66+g+f8eMkLqeDWSnKLDqYnxmJqxxrYf/taZ1hRrLVT0iJg+eh62EZY0qCSFlDWfHp0NtfUYdHuttqDRPMpvwXRa1DnGXZ1d2iYKb15NRySKoERZMnSd8a95PMHvQ+tzOBhba6A+BgylwSzqIH784sxuZsgcl7CtDh1KUERC1aAeXmf32tyalmJUNnb+aml711KMwO/mIUJ9NChhFpc9QqIRVh8Alq/wVftU/AYmZjk3F1kYVjShuHlR7ADPJLzxDzWnIPjOZlI3MGQxQ/Z5TCsb7W9gSnxAnD3NPBFbwHhMDX65edKQFMBeqzXzieOJ1zx7MwAVITNaqKFeYuk85H/xSVe2u6U8UoYnbk8sHv7ryU9qVc8z3SPVfzvwlp+Qw2ZdvXwMssMbwjjFQAkiWZbmQVMmny0geXi7WCQVc5cgLvPM0LUD5LGJsYwN8iKE2CbZnyglCJyZVLCuWIKuU9yJUaU33ACRCKIdcd0SwMUQwuSWUdUVnr2qxAMbZ4eYGCGTURwuFcv5vHKHzu/TD435Wjtm9jRct31eZz4=
#            skip_cleanup:   true
#            server:         https://test.pypi.org/legacy/
#            distributions:  "sdist bdist_wheel"
#            on:
#                tags: true

          - provider:       pypi
            user:           "eevee1"
            password:
                secure: qgDrBxXn2QVfyC1Q/TqCVlX9rLjuPQKhVyBtPKofn1NNysWLBDCWb0HJtdqntv4JLVY/CeeFPpJhWA476CUq/jvlkk+oS0WlKXucL9hDybo3cQqlAUrPx+Hxkxv4eNJTbKYG66+g+f8eMkLqeDWSnKLDqYnxmJqxxrYf/taZ1hRrLVT0iJg+eh62EZY0qCSFlDWfHp0NtfUYdHuttqDRPMpvwXRa1DnGXZ1d2iYKb15NRySKoERZMnSd8a95PMHvQ+tzOBhba6A+BgylwSzqIH784sxuZsgcl7CtDh1KUERC1aAeXmf32tyalmJUNnb+aml711KMwO/mIUJ9NChhFpc9QqIRVh8Alq/wVftU/AYmZjk3F1kYVjShuHlR7ADPJLzxDzWnIPjOZlI3MGQxQ/Z5TCsb7W9gSnxAnD3NPBFbwHhMDX65edKQFMBeqzXzieOJ1zx7MwAVITNaqKFeYuk85H/xSVe2u6U8UoYnbk8sHv7ryU9qVc8z3SPVfzvwlp+Qw2ZdvXwMssMbwjjFQAkiWZbmQVMmny0geXi7WCQVc5cgLvPM0LUD5LGJsYwN8iKE2CbZnyglCJyZVLCuWIKuU9yJUaU33ACRCKIdcd0SwMUQwuSWUdUVnr2qxAMbZ4eYGCGTURwuFcv5vHKHzu/TD435Wjtm9jRct31eZz4=
            serer:          https://upload.pypi.org/legacy/
            skip_cleanup:   true
            distributions:  "sdist bdist_wheel"
            on:
                tags: true
