language:                   python

python:                     3.6.7

cache:                      pip

jobs:
  include:
    - stage:                Testing

      install:
          - pip install -r requirements.txt

      script:
          - python Source/test.py

    - stage:                Deployment

      if:                   type != pull_request AND tag IS present

      install:
          - pip install pyminifier pbr

      before_script:
          - cd Source

      script:
          - find echo_lang -type f -name "*.py" -exec pyminifier --lzma --obfuscate-variables --outfile="{}" "{}" \;

      deploy:
          - provider:       pypi
            user:           "eevee1"
            password:       "$pypi_password"
            skip_cleanup:   true
            server:         https://test.pypi.org/legacy/
            distributions:  "sdist bdist_wheel"
            on:
                tags: true

          - provider:       pypi
            user:           "eevee1"
            password:       "$pypi_password"
            skip_cleanup:   true
            distributions:  "sdist bdist_wheel"
            on:
                tags: true

env:
    global:
        - secure: "z9W6Ge9kYETKeUOS101ChINqA8FwxRf4wvD2fF7E5CiNAO3IcFfi3jZr9lGmWY6FJf2lgx2TWu7k6EiqhXPhTZLOGj5Qst7sPVlXHyNzh+Uv1DjuVqk2WXjv3V/1QTXWKNde17HDnwtEwW7TQkd7cp8y0MAHrEbphA2/BTz/vvyEs357KWltTndpI1s+u1yX/gHAlOLetsUOJQXk9llaRrwr0/QbdHBzUdKLv+D5sN3jxYDnUuPPwdrxLsyLwXcX4MBaH21BUjlRTe1doY3+Zr2/4nx0EXyYkiCXJSLSd357GEpXtj2gTN3wPAok36LSJ+3gtRB/nyo+K24/PhgBW1NXtbrj7KRYHgkPmOVhs1JaU0cdvmvfdfzcLiSUc0dNgAWkBRNvQEpMtzoJLJeDRAoiP6LFpzf4NHx91EhNMXkZjau+FJvlgBsmI2VpCodMQ80q9ZKdk2e8xDAe7Sg40vAdc0ENmG2H7aFvGInxVyP6St813zHsWTqyAbTKcW51T+hjNwl0Jf3QP8E0aPNM3e9eAUbg+jscaCI2t0+ZYD+OHqFkpGLA1FkYDcNklscAHH/aC4/0qrrCqnich44E8Z/vu7aqX7S71kBei7HClr9CZXDWi+w/lmWBZijwrR9dxwO4RnL30+HvggdisnO0t8T8rVOcmnZXUM9Fa9C2y+0="
