language:                   python

python:                     3.6.7

cache:                      pip

jobs:
  include:
    - stage:                Testing

      install:
          - pip install -r requirements.txt

      script:
          - python Source/test.py

    - stage:                Deployment

      if:                   type != pull_request AND tag IS present

      install:
          - pip install pyminifier pbr

      before_script:
          - cd Source

      script:
          - find echo_lang -type f -name "*.py" -exec pyminifier --lzma --obfuscate-variables --outfile="{}" "{}" \;

      deploy:
          - provider:       pypi
            user:           "eevee1"
            password:       $pypi_password
            skip_cleanup:   true
            server:         https://test.pypi.org/legacy/
            distributions:  "sdist bdist_wheel"
            on:
                tags: true

          - provider:       pypi
            user:           "eevee1"
            password:       "$pypi_password"
            skip_cleanup:   true
            distributions:  "sdist bdist_wheel"
            on:
                tags: true

env:
    global:
        secure: x39dx+owcQ3jQwalT7pFbi6DaB7yAVww8GAL52d3D6DtVmKxZw9oUOAA7zIju1cp8krYxnqt5+IiBGkRCAl8cjOHZCQyy+PK7Qz0tVtoM88QUWm/lLqVB9ce9OosN2VtVgrhW3iBEpXGAajnZ0cn0gu95tdEzGLStZlbgIt6WTQgDCdcbLMR1H70ot84cOLTKu4sysmxDWP9Zu3T3ka506Yb6/695+NtxpcsP8zXVtYrEI0nVDuV3EmDnmmN3Vtho/a9YgD3OWuSgJw7qzt1xpaKWsZ3u3YwbIpBxXCRoH31LbPnNByrjunFioHrDGmO+8h8p+z9iEFfQ9aawpP12R5Vdlbo5x4BzAwEVEX9dYzb1pLm+6bK6whFYv7+GUfWOQ280XCEX9finPj9jCjFgsV36FQ5z5BHbGg79accxEsrKifjOkre881Gs2FKdiT5PXf5e7zgUCSxBiDOTEERnVyWQ4kqKIFr3DXDVz+U6YjJO5o9t4DoKxkaTCHibQaTMlZovn7G/FXzzmU6CfnzvyIhN8mm8QaN08ZTtuLeqkRDWnN9mLA2EOhygdCxZAS34j48NjeGniizKLWko8pnxQTHUM+M/FF3o3tMbKe8r7VZCjLsX1CKskRokYuWga8BvnT8AGdFDXqjAJeRG14IrFjxnt/rBpXXN3OZc7aro6o=
